### PR TITLE
mysterium TKL - fix deprecation warnings and defines errors

### PR DESCRIPTION
**Pull request by jbtrystram**
Updated the mysterium firmware to build without warnings

### CODE REVIEW

**Review by bmallory — APPROVED** [review]
did the same thing myself and was about to put the same PR

**Review by bmallory — APPROVED** [review]

**Comment by piit79** [comment]
Thank you!

**Comment by piit79** [comment]
I'd love to figure out some kind of workflow where I could rebase my changes on top of OG Mysterium...

**Comment by jbtrystram** [comment]
> I'd love to figure out some kind of workflow where I could rebase my changes on top of OG Mysterium...

you could simply have a branch and have the modifications in keeboards/coseyfannitutti/mysterium

**Pull request merged**
